apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: seu-usuario-docker/node-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "endereco-do-rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: node-api-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-api-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: node-api-secret
              key: DB_NAME